export const plTeamNameMap: { [key: string]: string } = {
  "Arsenal FC": "아스날",
  "Manchester City FC": "맨체스터 시티",
  "Newcastle United FC": "뉴캐슬 유나이티드",
  "Manchester United FC": "맨체스터 유나이티드",
  "Tottenham Hotspur FC": "토트넘 홋스퍼",
  "Aston Villa FC": "아스톤 빌라",
  "Brighton & Hove Albion FC": "브라이튼 호브 알비온",
  "Liverpool FC": "리버풀",
  "Brentford FC": "브렌트포드",
  "Fulham FC": "풀럼",
  "Chelsea FC": "첼시",
  "Crystal Palace FC": "크리스탈 팰리스",
  "Wolverhampton Wanderers FC": "울버햄튼 원더러스",
  "West Ham United FC": "웨스트햄 유나이티드",
  "AFC Bournemouth": "본머스",
  "Leeds United FC": "리즈 유나이티드",
  "Everton FC": "에버튼",
  "Nottingham Forest FC": "노팅엄 포레스트",
  "Leicester City FC": "레스터 시티",
  "Southampton FC": "사우스햄튼",
};

export const plPlayerNameMap: { [key: string]: string } = {
    "Erling Haaland": "엘링 홀란드",
    "Harry Kane": "해리 케인",
    "Ivan Toney": "아이반 토니",
    "Marcus Rashford": "마커스 래시포드",
    "Martinelli": "가브리엘 마르치넬리",
    "Mohamed Salah": "모하메드 살라",
    "Ollie Watkins": "올리 왓킨스",
    "Bukayo Saka": "부카요 사카",
    "Aleksandar Mitrović": "알렉산다르 미트로비치",
    "Rodrigo": "로드리고",
    "Callum Wilson": "칼럼 윌슨",
    "Martin Ødegaard": "마르틴 외데고르"
};

export const nationMap: { [key: string]: string } = {
    "Norway": "노르웨이",
    "England": "잉글랜드",
    "Egypt": "이집트",
    "Brazil": "브라질",
    "Poland": "폴란드",
    "France": "프랑스",
    "Spain": "스페인",
    "Turkey": "튀르키예",
    "Kosovo": "코소보",
    "Argentina": "아르헨티나",
    "Nigeria": "나이지리아",
    "Senegal": "세네갈",
    "Angola": "앙골라",
    "Georgia": "조지아",
    "Portugal": "포르투갈",
    "Paraguay": "파라과이",
    "Italy": "이탈리아",
}

export const laligaTeamNameMap: { [key: string]: string } = {
  "FC Barcelona": "FC 바르셀로나",
  "Club Atlético de Madrid": "아틀레티코 마드리드",
  "Real Madrid CF": "레알 마드리드",
  "Real Sociedad de Fútbol": "레알 소시에다드",
  "Villarreal CF": "비야레알",
  "Real Betis Balompié": "레알 베티스",
  "Girona FC": "지로나",
  "Athletic Club": "아틀레틱 빌바오",
  "Rayo Vallecano de Madrid": "라요 바예카노",
  "CA Osasuna": "오사수나",
  "Sevilla FC": "세비야",
  "RCD Mallorca": "마요르카",
  "RC Celta de Vigo": "셀타비고",
  "UD Almería": "알메리아",
  "Cádiz CF": "카디스 CF",
  "Real Valladolid CF": "레알 바야돌리드",
  "Valencia CF": "발렌시아",
  "Getafe CF": "헤타페",
  "RCD Espanyol de Barcelona": "RCD 에스파뇰",
  "Elche CF": "엘체"
}

export const serieTeamNameMap: { [key: string]: string } = {
  "SSC Napoli": "나폴리",
  "Juventus FC": "유벤투스",
  "SS Lazio": "라치오",
  "FC Internazionale Milano": "인터 밀란",
  "AC Milan": "AC 밀란",
  "Atalanta BC": "아탈란타",
  "AS Roma": "AS 로마",
  "ACF Fiorentina": "피오렌티나",
  "Udinese Calcio": "우디세네",
  "Bologna FC 1909": "볼로냐",
  "Torino FC": "토리노",
  "AC Monza": "AC 몬차",
  "US Sassuolo Calcio": "사수올로",
  "Empoli FC": "엠폴리",
  "US Salernitana 1919": "살레르니타나",
  "US Lecce": "레체",
  "Hellas Verona FC": "엘라스 베로나",
  "Spezia Calcio": "스페치아 칼초",
  "US Cremonese": "크레모네세",
  "UC Sampdoria": "삼프도리아",

}

export const laligaPlayerNameMap: { [key: string]: string } = {
  "Robert Lewandowski": "로베르트 레반도프스키",
  "Karim Benzema": "카림 벤제마",
  "Joselu": "호셀루",
  "Enes Ünal": "에네스 위날",
  "Álvaro Morata": "알바로 모라타",
  "Antoine Griezmann": "앙투안 그리즈만",
  "Vedat Muriqi": "베다트 무리키",
  "Valentín Castellanos": "발렌틴 카스테야노스",
  "Iago Aspas": "이아고 아스파스",
  "Borja Iglesias": "보르하 이글레시아스",
}

export const seriePlayerNameMap: { [key: string]: string } = {
  "Victor Osimhen": "빅터 오시멘",
  "Lautaro Martínez": "라우타로 마르티네스",
  "Boulaye Dia": "불라이 디아",
  "Ademola Lookman": "아데몰라 루크먼",
  "M'Bala Nzola": "음발라 은졸라",
  "Khvicha Kvaratskhelia": "흐비차 크바라츠헬리아",
  "Rafael Leão": "하파엘 레앙",
  "Antonio Sanabria": "안토니오 사나브리아",
  "Ciro Immobile": "치로 임모빌레",
  "Paulo Dybala": "파울로 디발라"
}
